# whitelist
branches:
  only:
    - master
language: java
jdk:
  - oraclejdk8
#before_install: unset SBT_OPTS JVM_OPTS
env:
  - PLAY_VERSION=1.3.7
install:
  - wget http://downloads.typesafe.com/typesafe-activator/1.3.7/typesafe-activator-1.3.7-minimal.zip
  - unzip -q typesafe-activator-1.3.7-minimal.zip
script: activator-1.3.7-minimal/activator test
