language: scala
before_install: unset SBT_OPTS JVM_OPTS
env:
  - PLAY_VERSION=1.3.4
before_script:
  - wget http://downloads.typesafe.com/typesafe-activator/${PLAY_VERSION}/typesafe-activator${PLAY_VERSION}-minimal.zip
  - unzip -q typesafe-activator-${PLAY_VERSION}-minimal.zip
script: activator-${PLAY_VERSION}-minimal/activator test
