language: scala
before_install: unset SBT_OPTS JVM_OPTS
env:
  - PLAY_VERSION=1.2.12
before_script:
  - wget http://downloads.typesafe.com/typesafe-activator/1.2.12/typesafe-activator-1.2.12-minimal.zip
  - unzip -q typesafe-activator-1.2.12-minimal.zip
script: activator-1.2.12-minimal/activator test